HAGGIN_FACE_API_KEY = ""
LLAMA_API_TOKEN = ""
OPENAI_KEY = ""
WHISPER_URL = "https://api-inference.huggingface.co/models/openai/whisper-large-v2"
KEY = ""
KEY_PHONE = ""
URL_ALL_MODELS = "https://api.gpt.mws.ru/v1/models"
URL_CHAT_COMPLETION = "https://api.gpt.mws.ru/v1/chat/completions"
URL_COMPLETION_APPEALS = "https://api.gpt.mws.ru/v1/completions"
URL_EMBEDDINGS = "https://api.gpt.mws.ru/v1/embeddings"
URL_PHONE = "http://apilayer.net/api/validate"
HEADERS = {"Authorization": f"Bearer {KEY}"}
HEADERS_OPENAI = {"Authorization": f"Bearer {OPENAI_KEY}"}
